# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: jhipstersampleapplication2
services:
  mysql:
    extends:
      file: ./mysql.yml
      service: mysql
  elasticsearch:
    extends:
      file: ./elasticsearch.yml
      service: elasticsearch
  kafka:
    extends:
      file: ./kafka.yml
      service: kafka
  zookeeper:
    extends:
      file: ./kafka.yml
      service: zookeeper
